/* Exercices d'« Orthographe du jour ».
   Le mot est DONNÉ (champ i) : on ne teste jamais le vocabulaire, mais
   uniquement la façon de l'écrire. Le joueur choisit entre la bonne
   graphie (r) et des graphies fausses plausibles (c). */
window.MOTUS_ORTHO = [
  {p:"Il a commis une grosse ___.",i:"erreur",r:["erreur"],c:["ereur","erreure","érreur"],e:"Deux r, et pas de e final."},
  {p:"Range-le dans l'___.",i:"armoire",r:["armoire"],c:["armoir","arrmoire","armouare"],e:"Un seul r, e final."},
  {p:"Elle lui a fait une ___.",i:"promesse",r:["promesse"],c:["promese","promaisse","prommesse"],e:"Deux s, comme tous les noms en -esse."},
  {p:"Le ___ est bien fermé.",i:"verrou",r:["verrou"],c:["verou","vérrou","verroux"],e:"Deux r, pas de x final au singulier."},
  {p:"Il a beaucoup de ___.",i:"tendresse",r:["tendresse"],c:["tendrese","tandresse","tendrèsse"],e:"Deux s, comme « paresse » ou « richesse »."},
  {p:"Une ___ importante.",i:"somme",r:["somme"],c:["some","sômme","sommes"],e:"Deux m, comme « pomme »."},
  {p:"Il a du ___.",i:"courage",r:["courage"],c:["couraje","courrage","couratge"],e:"Un seul r, terminaison en -age."},
  {p:"Elle a une bonne ___.",i:"mémoire",r:["mémoire"],c:["memoire","mémoir","méhmoire"],e:"Deux accents aigus, e final."},
  {p:"Une ___ difficile.",i:"difficulté",r:["difficulté"],c:["dificulté","difficultée","dificulter"],e:"Deux f, un seul c, pas de e final."},
  {p:"Il est très ___.",i:"intelligent",r:["intelligent"],c:["inteligent","intélligent","intelligeant"],e:"Deux l, terminaison en -ent."},
  {p:"Il a payé en ___.",i:"espèces",r:["espèces"],c:["espéces","espèce","espèsses"],e:"Accent grave sur le deuxième e."},
  {p:"Le ___ est complet.",i:"hôtel",r:["hôtel"],c:["hotel","hôtèl","hottel"],e:"H muet et accent circonflexe sur le o."},
  {p:"Il joue un ___ important.",i:"rôle",r:["rôle"],c:["role","rôlle","rolle"],e:"Accent circonflexe sur le o."},
  {p:"Ce plat a bon ___.",i:"goût",r:["goût"],c:["gout","goüt","goute"],e:"Accent circonflexe sur le u."},
  {p:"Le ___ du bateau.",i:"mât",r:["mât"],c:["mat","mâts","mate"],e:"Accent circonflexe : « mât » n'est pas « mat »."},
  {p:"Il est tombé de la ___.",i:"grêle",r:["grêle"],c:["grele","grèle","grêlle"],e:"Accent circonflexe sur le e."},
  {p:"Une ___ de sel.",i:"pincée",r:["pincée"],c:["pincé","pinçée","pincer"],e:"Nom féminin en -ée."},
  {p:"La ___ du film.",i:"durée",r:["durée"],c:["duré","durrée","duret"],e:"Nom féminin en -ée."},
  {p:"Un ___ de réflexion.",i:"délai",r:["délai"],c:["delai","délais","déllai"],e:"Accent aigu, pas de s au singulier."},
  {p:"Une ___ de sport.",i:"séance",r:["séance"],c:["seance","céance","séence"],e:"Accent aigu, terminaison en -ance."},
  {p:"L'eau vient du ___.",i:"puits",r:["puits"],c:["puit","puis","puix"],e:"Un t ET un s, même au singulier."},
  {p:"Il a mal au ___.",i:"dos",r:["dos"],c:["do","dot","doe"],e:"Le s final est muet mais obligatoire."},
  {p:"Il a gagné le ___.",i:"prix",r:["prix"],c:["pri","prit","prie"],e:"Le x final est muet."},
  {p:"Un ___ de fleurs.",i:"bouquet",r:["bouquet"],c:["bouqué","boucquet","bouquets"],e:"Le t final est muet."},
  {p:"Le ___ souffle fort.",i:"vent",r:["vent"],c:["ven","vant","vend"],e:"Le t final est muet."},
  {p:"Un ___ de blé.",i:"champ",r:["champ"],c:["chan","champs","cham"],e:"Le p final est muet, pas de s au singulier."},
  {p:"Il fait un ___ de la tête.",i:"signe",r:["signe"],c:["sine","signne","cigne"],e:"Le g est muet devant le n."},
  {p:"Elle a une belle ___.",i:"voix",r:["voix"],c:["voie","voi","vois"],e:"Le x final : « voix » n'est pas « voie »."},
  {p:"Cet ___ est utile.",i:"outil",r:["outil"],c:["outile","outill","outi"],e:"Le l final est muet."},
  {p:"C'est mon ___.",i:"travail",r:["travail"],c:["travaille","travai","travails"],e:"« Travail » le nom, « travaille » le verbe."},
  {p:"Le ___ sonne.",i:"réveil",r:["réveil"],c:["réveille","reveil","réveils"],e:"« Réveil » le nom, « réveille » le verbe."},
  {p:"Il a un profond ___.",i:"sommeil",r:["sommeil"],c:["someil","sommeille","sommeils"],e:"Deux m, « sommeil » sans e final."},
  {p:"Le ___ brille.",i:"soleil",r:["soleil"],c:["soleille","soléil","solleil"],e:"Terminaison en -eil sans e."},
  {p:"Une ___ de papier.",i:"feuille",r:["feuille"],c:["feuil","feuillle","feuile"],e:"Nom féminin : -euille avec e final."},
  {p:"Un ___ de musique.",i:"morceau",r:["morceau"],c:["morcau","morceaux","morsceau"],e:"Terminaison en -eau, sans x au singulier."},
  {p:"Il porte un ___.",i:"chapeau",r:["chapeau"],c:["chapau","chapeaux","chappeau"],e:"Terminaison en -eau."},
  {p:"Le ___ de la maison.",i:"toit",r:["toit"],c:["toi","toits","toie"],e:"Le t final : « toit » n'est pas « toi »."},
  {p:"Du sucre en ___.",i:"poudre",r:["poudre"],c:["poudres","poudrre","pouddre"],e:"Terminaison en -dre."},
  {p:"Il habite près de la ___.",i:"mer",r:["mer"],c:["mère","maire","mers"],e:"La grande étendue d'eau : « mer »."},
  {p:"Sa ___ est venue.",i:"mère",r:["mère"],c:["mer","maire","mairre"],e:"Le parent : « mère », avec accent grave."},
  {p:"Le ___ de la commune.",i:"maire",r:["maire"],c:["mer","mère","mairre"],e:"L'élu : « maire »."},
  {p:"Un ___ de commerce.",i:"fonds",r:["fonds"],c:["fond","font","fon"],e:"Le capital : « fonds » avec un s."},
  {p:"Le ___ de la piscine.",i:"fond",r:["fond"],c:["fonds","font","fon"],e:"La partie basse : « fond » sans s."},
  {p:"Une ___ en or.",i:"chaîne",r:["chaîne"],c:["chêne","chaine","chènne"],e:"La suite d'anneaux : « chaîne » avec î."},
  {p:"Le ___ est un arbre.",i:"chêne",r:["chêne"],c:["chaîne","chène","chenne"],e:"L'arbre : « chêne » avec ê."},
  {p:"Il a ___ insisté qu'il a gagné.",i:"tant",r:["tant"],c:["temps","tan","tend"],e:"La quantité : « tant »."},
  {p:"Je n'ai pas le ___.",i:"temps",r:["temps"],c:["tant","tems","temp"],e:"La durée : « temps » avec p et s."},
  {p:"Il monte sur un ___.",i:"cheval",r:["cheval"],c:["chevale","chevaux","ch'val"],e:"Singulier : « cheval »."},
  {p:"Plusieurs ___ au pré.",i:"chevaux",r:["chevaux"],c:["chevals","chevaus","chevaud"],e:"« Cheval » fait « chevaux »."},
  {p:"Il lit les ___.",i:"journaux",r:["journaux"],c:["journals","journeaux","journaus"],e:"Les noms en -al font -aux."},
  {p:"Des ___ anciens.",i:"châteaux",r:["châteaux"],c:["chateaux","châteaus","châtaux"],e:"Accent circonflexe et x au pluriel."},
  {p:"De gros ___ dans la rue.",i:"travaux",r:["travaux"],c:["travails","travaus","travailles"],e:"« Travail » fait « travaux »."},
  {p:"Les ___ de l'église.",i:"vitraux",r:["vitraux"],c:["vitrails","vitreaux","vitrauds"],e:"« Vitrail » fait « vitraux »."},
  {p:"Des ___ bien rangés.",i:"bureaux",r:["bureaux"],c:["bureaus","buraux","burreaux"],e:"Les noms en -eau prennent un x."},
  {p:"Il faut que tu ___.",i:"travailles",r:["travailles"],c:["travail","travaille","travaillent"],e:"Verbe à la 2e personne : « travailles »."},
  {p:"Mon ___ me plaît.",i:"emploi",r:["emploi"],c:["emplois","employe","emploie"],e:"Le nom : « emploi » sans e."},
  {p:"Il ___ dix personnes.",i:"emploie",r:["emploie"],c:["emploi","emplois","employe"],e:"Le verbe : « emploie » avec e."},
  {p:"Il a fait un ___.",i:"essai",r:["essai"],c:["essais","éssai","essaie"],e:"Le nom : « essai » sans e."},
  {p:"Il ___ de comprendre.",i:"essaie",r:["essaie"],c:["essai","essais","essaye"],e:"Le verbe : « essaie » avec e."},
  {p:"Un ___ de foot.",i:"match",r:["match"],c:["matche","matchs","matsh"],e:"Mot emprunté à l'anglais, sans e."},
  {p:"Il a ___ son travail.",i:"achevé",r:["achevé"],c:["acheve","achevait","acchevé"],e:"Participe passé en -é."},
  {p:"Une ___ heureuse.",i:"issue",r:["issue"],c:["issu","issues","yssue"],e:"Nom féminin : « issue » avec e."},
  {p:"Il est ___ de partir.",i:"censé",r:["censé"],c:["sensé","cencé","sancé"],e:"« Censé » = supposé ; « sensé » = plein de bon sens."},
  {p:"Un homme ___.",i:"sensé",r:["sensé"],c:["censé","cencé","sansé"],e:"« Sensé » = qui a du bon sens."},
  {p:"Il l'a fait ___.",i:"exprès",r:["exprès"],c:["expres","express","exprés"],e:"Accent grave, s final."},
  {p:"Un train ___.",i:"express",r:["express"],c:["exprès","expres","expresse"],e:"Deux s : le train rapide."},
  {p:"Elle a ___ raison.",i:"eu",r:["eu"],c:["eue","u","eut"],e:"Participe passé de « avoir » : « eu »."},
  {p:"Il ___ tard hier.",i:"rentra",r:["rentra"],c:["rentras","rentrat","rentrait"],e:"Passé simple, 3e personne."},
  {p:"Une ___ de bon sens.",i:"question",r:["question"],c:["questionne","quéstion","questions"],e:"Terminaison en -tion."},
  {p:"Il a pris une ___.",i:"décision",r:["décision"],c:["decision","décission","décisions"],e:"Terminaison en -sion, un seul s."},
  {p:"Il fait beaucoup d'___ au sport.",i:"efforts",r:["efforts"],c:["éfforts","efors","effords"],e:"Deux f, t muet, s du pluriel."},
  {p:"Ouvre le ___ de la cuisine.",i:"robinet",r:["robinet"],c:["robbinet","robinnet","robiné"],e:"Un seul b, un seul n, t final."},
  {p:"Il a une ___ de tête.",i:"migraine",r:["migraine"],c:["migrène","migrainne","mygraine"],e:"Terminaison en -aine."},
  {p:"Prends ton ___ de pluie.",i:"parapluie",r:["parapluie"],c:["parraplui","paraplui","parapluis"],e:"Un seul r, e final."},
  {p:"Le ___ traverse la rue.",i:"piéton",r:["piéton"],c:["piétton","piéthon","piètton"],e:"Accent aigu, un seul t."},
  {p:"Il porte des ___.",i:"lunettes",r:["lunettes"],c:["lunètes","lunetes","lunnettes"],e:"Un seul n, deux t."},
  {p:"L'___ vole haut.",i:"aigle",r:["aigle"],c:["aigl","aiggle","égle"],e:"Terminaison en -gle."},
  {p:"Une ___ de lait.",i:"bouteille",r:["bouteille"],c:["bouteil","boutteille","bouteile"],e:"Un seul t, terminaison en -eille."},
  {p:"Il fait ses ___ scolaires.",i:"devoirs",r:["devoirs"],c:["devoires","dévoirs","devoir's"],e:"Terminaison en -oirs, sans e."},
  {p:"La ___ est sur la table.",i:"casserole",r:["casserole"],c:["caserole","cassserole","casserolle"],e:"Deux s, un seul l."},
  {p:"Un ___ de pommes.",i:"panier",r:["panier"],c:["pannier","panié","panniers"],e:"Un seul n, r final muet."},
  {p:"Il a une grosse ___ au doigt.",i:"ampoule",r:["ampoule"],c:["empoule","ampoulle","ampoul"],e:"M devant p."},
  {p:"Le ___ d'anniversaire.",i:"gâteau",r:["gâteau"],c:["gateau","gâtteau","gâteaux"],e:"Accent circonflexe, -eau au singulier."},
  {p:"Une grande ___ de sable.",i:"étendue",r:["étendue"],c:["étendu","éttendue","étandue"],e:"Nom féminin en -ue."},
  {p:"La ___ est tombée.",i:"neige",r:["neige"],c:["nège","neije","neigge"],e:"Pas d'accent : « ei » se prononce è."},
  {p:"Il est allé à la ___.",i:"fête",r:["fête"],c:["fète","fete","faite"],e:"Accent circonflexe : la célébration."},
  {p:"Elle a les ___ bleus.",i:"yeux",r:["yeux"],c:["yeus","yeuxs","ieux"],e:"Pluriel irrégulier de « œil »."},
  {p:"Il a mal à la ___.",i:"tête",r:["tête"],c:["tète","tete","têtte"],e:"Accent circonflexe sur le e."},
  {p:"Une tarte à la ___ pâtissière.",i:"crème",r:["crème"],c:["crême","creme","crèmme"],e:"Accent grave, pas circonflexe."},
  {p:"Il a une ___ blanche.",i:"chemise",r:["chemise"],c:["chémise","chemize","chemmise"],e:"Pas d'accent, s prononcé z."},
  {p:"Le ___ de la classe.",i:"élève",r:["élève"],c:["élêve","eleve","élèv"],e:"Accent aigu puis grave."},
  {p:"Elle chante une ___.",i:"chanson",r:["chanson"],c:["chançon","chansson","chanssons"],e:"Un seul s prononcé s après n."},
  {p:"Il y a un ___ dans le ciel.",i:"arc-en-ciel",r:["arc-en-ciel"],c:["arc en ciel","arc-en-cièl","arcenciel"],e:"Deux traits d'union."},
  {p:"C'est la ___ du film.",i:"fin",r:["fin"],c:["faim","feint","fain"],e:"La conclusion : « fin »."},
  {p:"J'ai très ___.",i:"faim",r:["faim"],c:["fin","feint","faint"],e:"L'envie de manger : « faim »."},
  {p:"Il a mangé un ___ de pain.",i:"bout",r:["bout"],c:["bou","boue","bous"],e:"Le t final est muet."},
  {p:"Une ___ de terre.",i:"motte",r:["motte"],c:["mote","mottes","motteu"],e:"Deux t, e final."},
  {p:"Il a ___ enfants.",i:"trois",r:["trois"],c:["troi","troix","trois'"],e:"Le s final est muet."},
  {p:"Le ___ du chien.",i:"poil",r:["poil"],c:["poile","poêl","poils"],e:"Le nom masculin, sans e."},
  {p:"Il fait ___ dehors.",i:"froid",r:["froid"],c:["froit","frois","froi"],e:"Le d final est muet."},
  {p:"Le ___ de la guitare.",i:"son",r:["son"],c:["sont","sons","sonn"],e:"Le bruit : « son »."},
  {p:"Ils ___ contents.",i:"sont",r:["sont"],c:["son","sons","sonts"],e:"Le verbe être : « sont »."},
  {p:"Une ___ de chocolat.",i:"tablette",r:["tablette"],c:["tablète","tablett","tabllette"],e:"Deux t, e final."},
  {p:"Un ___ de laine.",i:"tricot",r:["tricot"],c:["trico","tricau","tricots"],e:"Le t final est muet."},
  {p:"Le ___ de la forêt.",i:"loup",r:["loup"],c:["lou","loue","loups"],e:"Le p final est muet."},
  {p:"Il ___ du piano.",i:"joue",r:["joue"],c:["joux","jou","joues"],e:"Le verbe : « il joue »."},
  {p:"Il a une ___ rouge.",i:"joue",r:["joue"],c:["jou","joux","joues"],e:"La partie du visage : « joue »."},
  {p:"Elle a ___ la porte.",i:"fermé",r:["fermé"],c:["fermer","fermée","fermez"],e:"Participe passé avec « avoir » : « fermé »."},
  {p:"Il faut ___ la porte.",i:"fermer",r:["fermer"],c:["fermé","fermez","fermée"],e:"Après « il faut », l'infinitif : « fermer »."},
  {p:"Il met un ___ au bout de sa ligne.",i:"ver",r:["ver"],c:["vers","verre","vert"],e:"L'animal : « ver »."},
  {p:"Il boit un ___ d'eau.",i:"verre",r:["verre"],c:["ver","vers","vert"],e:"Le récipient : « verre »."},
  {p:"L'herbe est ___.",i:"verte",r:["verte"],c:["vertes","vairte","verre"],e:"La couleur au féminin : « verte »."},
  {p:"Il va ___ la gare.",i:"vers",r:["vers"],c:["ver","verre","vert"],e:"La direction : « vers »."},
  {p:"Il a une ___ sur la tête.",i:"bosse",r:["bosse"],c:["boss","bose","bossse"],e:"Deux s, e final."},
  {p:"Le ___ de la route.",i:"bord",r:["bord"],c:["bort","bore","bords"],e:"Le d final est muet."},
  {p:"Elle ___ trop vite.",i:"court",r:["court"],c:["cours","cour","courre"],e:"Le verbe : « elle court »."},
  {p:"La ___ de l'école.",i:"cour",r:["cour"],c:["court","cours","courre"],e:"L'espace ouvert : « cour »."},
  {p:"J'ai un ___ de maths.",i:"cours",r:["cours"],c:["cour","court","courts"],e:"La leçon : « cours »."},
  {p:"Une ___ de pain.",i:"tranche",r:["tranche"],c:["tranch","tranche's","tranches"],e:"E final au singulier."},
  {p:"Il ___ la vérité.",i:"dit",r:["dit"],c:["di","dis","dît"],e:"Le verbe au présent : « il dit »."},
  {p:"Des ___ de la mer.",i:"bateaux",r:["bateaux"],c:["bateaus","batteaux","batéaux"],e:"Pluriel en -eaux."},
  {p:"Ils ont les ___ sales.",i:"genoux",r:["genoux"],c:["genous","genouxs","genoues"],e:"« Genou » fait « genoux »."},
  {p:"Des ___ précieux.",i:"bijoux",r:["bijoux"],c:["bijous","bijouxs","bijoues"],e:"« Bijou » fait « bijoux »."},
  {p:"Les ___ dansent.",i:"hiboux",r:["hiboux"],c:["hibous","hibouxs","hiboues"],e:"« Hibou » fait « hiboux »."},
  {p:"Des ___ de terre.",i:"trous",r:["trous"],c:["troux","troues","trou's"],e:"« Trou » fait « trous », sans x."},
  {p:"Des ___ de gâteau.",i:"morceaux",r:["morceaux"],c:["morceaus","morçeaux","morceau"],e:"Pluriel en -eaux."},
  {p:"Des ___ pointus.",i:"cailloux",r:["cailloux"],c:["caillous","caillouxs","caïlloux"],e:"« Caillou » fait « cailloux »."},
  {p:"Il a deux ___.",i:"animaux",r:["animaux"],c:["animals","animeaux","animaus"],e:"« Animal » fait « animaux »."},
  {p:"Les ___ du stade.",i:"festivals",r:["festivals"],c:["festivaux","festivals'","festiveaux"],e:"Exception : « festival » fait « festivals »."},
  {p:"Des ___ de voitures.",i:"carnavals",r:["carnavals"],c:["carnavaux","carnaval","carnavales"],e:"Exception : « carnaval » fait « carnavals »."},
  {p:"Il est ___ de monde.",i:"plein",r:["plein"],c:["plain","plin","pleint"],e:"Terminaison en -ein."},
  {p:"Il fait ___ de choses.",i:"beaucoup",r:["beaucoup"],c:["baucoup","beaucou","beaucoups"],e:"Le p final est muet."},
  {p:"Il est arrivé ___.",i:"hier",r:["hier"],c:["hièr","yer","ier"],e:"H muet initial."},
  {p:"C'est ___ vrai.",i:"vraiment",r:["vraiment"],c:["vraiement","vraimant","vréement"],e:"Pas de e avant -ment."},
  {p:"Il parle ___.",i:"gentiment",r:["gentiment"],c:["gentilment","gentiement","jentiment"],e:"Pas de l ni de e avant -ment."},
  {p:"Il court ___.",i:"rapidement",r:["rapidement"],c:["rapidemant","rappidement","rapidment"],e:"Terminaison en -ement."},
  {p:"Il est ___ gentil.",i:"très",r:["très"],c:["trés","tres","trè"],e:"Accent grave, s final."},
  {p:"___ je pars.",i:"Aujourd'hui",r:["aujourd'hui"],c:["aujourdhui","aujourd'hui'","aujour d'hui"],e:"Apostrophe entre d et h."},
  {p:"Il a un ___ poussé.",i:"cheveu",r:["cheveu"],c:["cheveux","chevu","chevo"],e:"Singulier : « cheveu » sans x."},
  {p:"Il faut ___ rire.",i:"en",r:["en"],c:["an","han","em"],e:"La préposition : « en »."}
];
