/* Exercices d'« Orthographe du jour ».
   Le mot est DONNÉ (champ i) : on ne teste jamais le vocabulaire, mais
   uniquement la façon de l'écrire. Le joueur choisit entre la bonne
   graphie (r) et des graphies fausses plausibles (c). */
window.MOTUS_ORTHO = [
  {p:"Il a commis une grosse ___.",i:"erreur",r:["erreur"],c:["ereur","erreure","érreur"],e:"Deux r, et pas de e final."},
  {p:"Range-le dans l'___.",i:"armoire",r:["armoire"],c:["armoir","arrmoire","armouare"],e:"Un seul r, e final."},
  {p:"Elle lui a fait une ___.",i:"promesse",r:["promesse"],c:["promese","promaisse","prommesse"],e:"Deux s, comme tous les noms en -esse."},
  {p:"Le ___ est bien fermé.",i:"verrou",r:["verrou"],c:["verou","vérrou","verroux"],e:"Deux r, pas de x final au singulier."},
  {p:"Il a beaucoup de ___.",i:"tendresse",r:["tendresse"],c:["tendrese","tandresse","tendrèsse"],e:"Deux s, comme « paresse » ou « richesse »."},
  {p:"Une ___ importante.",i:"somme",r:["somme"],c:["some","sômme","sommes"],e:"Deux m, comme « pomme »."},
  {p:"Il a du ___.",i:"courage",r:["courage"],c:["couraje","courrage","couratge"],e:"Un seul r, terminaison en -age."},
  {p:"Elle a une bonne ___.",i:"mémoire",r:["mémoire"],c:["memoire","mémoir","méhmoire"],e:"Deux accents aigus, e final."},
  {p:"Cet exercice présente une ___.",i:"difficulté",r:["difficulté"],c:["dificulté","difficultée","dificulter"],e:"Deux f, un seul c, pas de e final."},
  {p:"Il est très ___.",i:"intelligent",r:["intelligent"],c:["inteligent","intélligent","intelligeant"],e:"Deux l, terminaison en -ent."},
  {p:"Il a payé en ___.",i:"espèces",r:["espèces"],c:["espéces","espèce","espèsses"],e:"Accent grave sur le deuxième e."},
  {p:"Notre ___ est complet ce soir.",i:"hôtel",r:["hôtel"],c:["hotel","hôtèl","hottel"],e:"H muet et accent circonflexe sur le o."},
  {p:"Il joue un ___ important.",i:"rôle",r:["rôle"],c:["role","rôlle","rolle"],e:"Accent circonflexe sur le o."},
  {p:"Ce plat a bon ___.",i:"goût",r:["goût"],c:["goüt","goute","gôut"],e:"Accent circonflexe sur le u."},
  {p:"Le ___ du bateau.",i:"mât",r:["mât"],c:["mat","mâts","mate"],e:"Accent circonflexe : « mât » n'est pas « mat »."},
  {p:"Il est tombé de la ___.",i:"grêle",r:["grêle"],c:["grele","grèle","grêlle"],e:"Accent circonflexe sur le e."},
  {p:"Une ___ de sel.",i:"pincée",r:["pincée"],c:["pincé","pinçée","pincer"],e:"Nom féminin en -ée."},
  {p:"La ___ du film.",i:"durée",r:["durée"],c:["duré","durrée","duret"],e:"Nom féminin en -ée."},
  {p:"Un ___ de réflexion.",i:"délai",r:["délai"],c:["delai","délais","déllai"],e:"Accent aigu, pas de s au singulier."},
  {p:"Une ___ de sport.",i:"séance",r:["séance"],c:["seance","céance","séence"],e:"Accent aigu, terminaison en -ance."},
  {p:"L'eau vient du ___.",i:"puits",r:["puits"],c:["puit","puis","puix"],e:"Un t ET un s, même au singulier."},
  {p:"Il a mal au ___.",i:"dos",r:["dos"],c:["do","dot","doe"],e:"Le s final est muet mais obligatoire."},
  {p:"Il a gagné le ___.",i:"prix",r:["prix"],c:["pri","prit","prie"],e:"Le x final est muet."},
  {p:"Un ___ de fleurs.",i:"bouquet",r:["bouquet"],c:["bouqué","boucquet","bouquets"],e:"Le t final est muet."},
  {p:"Le ___ souffle fort.",i:"vent",r:["vent"],c:["ven","vant","vend"],e:"Le t final est muet."},
  {p:"Un ___ de blé.",i:"champ",r:["champ"],c:["chan","champs","cham"],e:"Le p final est muet, pas de s au singulier."},
  {p:"Il fait un ___ de la tête.",i:"signe",r:["signe"],c:["sine","signne","cigne"],e:"Le g est muet devant le n."},
  {p:"Elle a une belle ___.",i:"voix",r:["voix"],c:["voie","voi","vois"],e:"Le x final : « voix » n'est pas « voie »."},
  {p:"Cet ___ est utile.",i:"outil",r:["outil"],c:["outile","outill","outi"],e:"Le l final est muet."},
  {p:"C'est mon ___.",i:"travail",r:["travail"],c:["travaille","travai","travails"],e:"« Travail » le nom, « travaille » le verbe."},
  {p:"Le ___ sonne.",i:"réveil",r:["réveil"],c:["réveille","reveil","réveils"],e:"« Réveil » le nom, « réveille » le verbe."},
  {p:"Il a un profond ___.",i:"sommeil",r:["sommeil"],c:["someil","sommeille","sommeils"],e:"Deux m, « sommeil » sans e final."},
  {p:"Le ___ brille.",i:"soleil",r:["soleil"],c:["soleille","soléil","solleil"],e:"Terminaison en -eil sans e."},
  {p:"Une ___ de papier.",i:"feuille",r:["feuille"],c:["feuil","feuillle","feuile"],e:"Nom féminin : -euille avec e final."},
  {p:"Un ___ de musique.",i:"morceau",r:["morceau"],c:["morcau","morceaux","morsceau"],e:"Terminaison en -eau, sans x au singulier."},
  {p:"Il porte un ___.",i:"chapeau",r:["chapeau"],c:["chapau","chapeaux","chappeau"],e:"Terminaison en -eau."},
  {p:"Le ___ de la maison.",i:"toit",r:["toit"],c:["toi","toits","toie"],e:"Le t final : « toit » n'est pas « toi »."},
  {p:"Du sucre en ___.",i:"poudre",r:["poudre"],c:["poudres","poudrre","pouddre"],e:"Terminaison en -dre."},
  {p:"Il habite près de la ___.",i:"mer",r:["mer"],c:["mère","maire","mers"],e:"La grande étendue d'eau : « mer »."},
  {p:"Sa ___ est venue.",i:"mère",r:["mère"],c:["mer","maire","mairre"],e:"Le parent : « mère », avec accent grave."},
  {p:"Le ___ de la commune.",i:"maire",r:["maire"],c:["mer","mère","mairre"],e:"L'élu : « maire »."},
  {p:"Un ___ de commerce.",i:"fonds",r:["fonds"],c:["fond","font","fon"],e:"Le capital : « fonds » avec un s."},
  {p:"Le ___ de la piscine.",i:"fond",r:["fond"],c:["fonds","font","fon"],e:"La partie basse : « fond » sans s."},
  {p:"Une ___ en or.",i:"chaîne",r:["chaîne"],c:["chêne","chaîme","chènne"],e:"La suite d'anneaux : « chaîne » avec î."},
  {p:"Le ___ est un arbre.",i:"chêne",r:["chêne"],c:["chaîne","chène","chenne"],e:"L'arbre : « chêne » avec ê."},
  {p:"Il a ___ insisté qu'il a gagné.",i:"tant",r:["tant"],c:["temps","tan","tend"],e:"La quantité : « tant »."},
  {p:"Je n'ai pas le ___.",i:"temps",r:["temps"],c:["tant","tems","temp"],e:"La durée : « temps » avec p et s."},
  {p:"Il monte sur un ___.",i:"cheval",r:["cheval"],c:["chevale","chevaux","ch'val"],e:"Singulier : « cheval »."},
  {p:"Plusieurs ___ au pré.",i:"chevaux",r:["chevaux"],c:["chevals","chevaus","chevaud"],e:"« Cheval » fait « chevaux »."},
  {p:"Il lit les ___.",i:"journaux",r:["journaux"],c:["journals","journeaux","journaus"],e:"Les noms en -al font -aux."},
  {p:"Des ___ anciens.",i:"châteaux",r:["châteaux"],c:["chateaux","châteaus","châtaux"],e:"Accent circonflexe et x au pluriel."},
  {p:"De gros ___ dans la rue.",i:"travaux",r:["travaux"],c:["travails","travaus","travailles"],e:"« Travail » fait « travaux »."},
  {p:"Les ___ de l'église.",i:"vitraux",r:["vitraux"],c:["vitrails","vitreaux","vitrauds"],e:"« Vitrail » fait « vitraux »."},
  {p:"Des ___ bien rangés.",i:"bureaux",r:["bureaux"],c:["bureaus","buraux","burreaux"],e:"Les noms en -eau prennent un x."},
  {p:"Il faut que tu ___.",i:"travailles",r:["travailles"],c:["travail","travaille","travaillent"],e:"Verbe à la 2e personne : « travailles »."},
  {p:"Mon ___ me plaît.",i:"emploi",r:["emploi"],c:["emplois","employe","emploie"],e:"Le nom : « emploi » sans e."},
  {p:"Il ___ dix personnes.",i:"emploie",r:["emploie"],c:["emploi","emplois","employe"],e:"Le verbe : « emploie » avec e."},
  {p:"Il a fait un ___.",i:"essai",r:["essai"],c:["essais","éssai","essaie"],e:"Le nom : « essai » sans e."},
  {p:"Il ___ de comprendre.",i:"essaie",r:["essaie"],c:["essai","essais","essait"],e:"Le verbe : « essaie » avec e."},
  {p:"Un ___ de foot.",i:"match",r:["match"],c:["matche","matchs","matsh"],e:"Mot emprunté à l'anglais, sans e."},
  {p:"Il a ___ son travail.",i:"achevé",r:["achevé"],c:["acheve","achevait","acchevé"],e:"Participe passé en -é."},
  {p:"Une ___ heureuse.",i:"issue",r:["issue"],c:["issu","issues","yssue"],e:"Nom féminin : « issue » avec e."},
  {p:"Il est ___ partir demain.",i:"censé",r:["censé"],c:["sensé","cencé","sancé"],e:"« Censé » = supposé ; « sensé » = plein de bon sens."},
  {p:"Un homme ___.",i:"sensé",r:["sensé"],c:["censé","cencé","sansé"],e:"« Sensé » = qui a du bon sens."},
  {p:"Il l'a fait ___.",i:"exprès",r:["exprès"],c:["expres","express","exprés"],e:"Accent grave, s final."},
  {p:"Un train ___.",i:"express",r:["express"],c:["exprès","expres","expresse"],e:"Deux s : le train rapide."},
  {p:"Elle a ___ raison.",i:"eu",r:["eu"],c:["eue","u","eut"],e:"Participe passé de « avoir » : « eu »."},
  {p:"Il ___ tard hier.",i:"rentra",r:["rentra"],c:["rentras","rentrat","rantra"],e:"Passé simple, 3e personne."},
  {p:"Une ___ de bon sens.",i:"question",r:["question"],c:["questionne","quéstion","questions"],e:"Terminaison en -tion."},
  {p:"Il a pris une ___.",i:"décision",r:["décision"],c:["decision","décission","décisions"],e:"Terminaison en -sion, un seul s."},
  {p:"Il fait beaucoup d'___ au sport.",i:"efforts",r:["efforts"],c:["éfforts","efors","effords"],e:"Deux f, t muet, s du pluriel."},
  {p:"Ouvre le ___ de la cuisine.",i:"robinet",r:["robinet"],c:["robbinet","robinnet","robiné"],e:"Un seul b, un seul n, t final."},
  {p:"Il a une forte ___.",i:"migraine",r:["migraine"],c:["migrène","migrainne","mygraine"],e:"Terminaison en -aine."},
  {p:"Prends ton ___, il pleut.",i:"parapluie",r:["parapluie"],c:["parraplui","paraplui","parapluis"],e:"Un seul r, e final."},
  {p:"Le ___ traverse la rue.",i:"piéton",r:["piéton"],c:["piétton","piéthon","piètton"],e:"Accent aigu, un seul t."},
  {p:"Il porte des ___.",i:"lunettes",r:["lunettes"],c:["lunètes","lunetes","lunnettes"],e:"Un seul n, deux t."},
  {p:"L'___ vole haut.",i:"aigle",r:["aigle"],c:["aigl","aiggle","égle"],e:"Terminaison en -gle."},
  {p:"Une ___ de lait.",i:"bouteille",r:["bouteille"],c:["bouteil","boutteille","bouteile"],e:"Un seul t, terminaison en -eille."},
  {p:"Il fait ses ___ scolaires.",i:"devoirs",r:["devoirs"],c:["devoires","dévoirs","devoir's"],e:"Terminaison en -oirs, sans e."},
  {p:"La ___ est sur la table.",i:"casserole",r:["casserole"],c:["caserole","cassserole","casserolle"],e:"Deux s, un seul l."},
  {p:"Un ___ de pommes.",i:"panier",r:["panier"],c:["pannier","panié","panniers"],e:"Un seul n, r final muet."},
  {p:"Il a une grosse ___ au doigt.",i:"ampoule",r:["ampoule"],c:["empoule","ampoulle","ampoul"],e:"M devant p."},
  {p:"Le ___ d'anniversaire.",i:"gâteau",r:["gâteau"],c:["gateau","gâtteau","gâteaux"],e:"Accent circonflexe, -eau au singulier."},
  {p:"Une grande ___ de sable.",i:"étendue",r:["étendue"],c:["étendu","éttendue","étandue"],e:"Nom féminin en -ue."},
  {p:"La ___ est tombée.",i:"neige",r:["neige"],c:["nège","neije","neigge"],e:"Pas d'accent : « ei » se prononce è."},
  {p:"Il est allé à la ___.",i:"fête",r:["fête"],c:["fète","fete","faite"],e:"Accent circonflexe : la célébration."},
  {p:"Elle a les ___ bleus.",i:"yeux",r:["yeux"],c:["yeus","yeuxs","ieux"],e:"Pluriel irrégulier de « œil »."},
  {p:"Il a mal à la ___.",i:"tête",r:["tête"],c:["tète","tete","têtte"],e:"Accent circonflexe sur le e."},
  {p:"Une tarte à la ___ pâtissière.",i:"crème",r:["crème"],c:["crême","creme","crèmme"],e:"Accent grave, pas circonflexe."},
  {p:"Il a une ___ blanche.",i:"chemise",r:["chemise"],c:["chémise","chemize","chemmise"],e:"Pas d'accent, s prononcé z."},
  {p:"C'est un ___ très sage.",i:"élève",r:["élève"],c:["élêve","eleve","élèv"],e:"Accent aigu puis grave."},
  {p:"Elle chante une ___.",i:"chanson",r:["chanson"],c:["chançon","chansson","chanssons"],e:"Un seul s prononcé s après n."},
  {p:"Il y a un ___ dans le ciel.",i:"arc-en-ciel",r:["arc-en-ciel"],c:["arc en ciel","arc-en-cièl","arcenciel"],e:"Deux traits d'union."},
  {p:"C'est la ___ du film.",i:"fin",r:["fin"],c:["faim","feint","fain"],e:"La conclusion : « fin »."},
  {p:"J'ai très ___.",i:"faim",r:["faim"],c:["fin","feint","faint"],e:"L'envie de manger : « faim »."},
  {p:"Il a mangé un ___ de pain.",i:"bout",r:["bout"],c:["bou","boue","bous"],e:"Le t final est muet."},
  {p:"Une ___ de terre.",i:"motte",r:["motte"],c:["mote","mottes","motteu"],e:"Deux t, e final."},
  {p:"Il a ___ enfants.",i:"trois",r:["trois"],c:["troi","troix","trois'"],e:"Le s final est muet."},
  {p:"Le ___ du chien.",i:"poil",r:["poil"],c:["poile","poêl","poils"],e:"Le nom masculin, sans e."},
  {p:"Il fait ___ dehors.",i:"froid",r:["froid"],c:["froit","frois","froi"],e:"Le d final est muet."},
  {p:"Le ___ de la guitare.",i:"son",r:["son"],c:["sont","sons","sonn"],e:"Le bruit : « son »."},
  {p:"Ils ___ contents.",i:"sont",r:["sont"],c:["son","sons","sonts"],e:"Le verbe être : « sont »."},
  {p:"Une ___ de chocolat.",i:"tablette",r:["tablette"],c:["tablète","tablett","tabllette"],e:"Deux t, e final."},
  {p:"Un ___ de laine.",i:"tricot",r:["tricot"],c:["trico","tricau","tricots"],e:"Le t final est muet."},
  {p:"Le ___ de la forêt.",i:"loup",r:["loup"],c:["lou","loue","loups"],e:"Le p final est muet."},
  {p:"Il ___ du piano.",i:"joue",r:["joue"],c:["joux","jou","joues"],e:"Le verbe : « il joue »."},
  {p:"Il habite dans une grande ___.",i:"ville",r:["ville"],c:["vile","vil","villes"],e:"Deux l : « ville » ; « vile » est un autre mot."},
  {p:"Elle a ___ la porte.",i:"fermé",r:["fermé"],c:["fermer","fermée","fermez"],e:"Participe passé avec « avoir » : « fermé »."},
  {p:"Il faut ___ la porte.",i:"fermer",r:["fermer"],c:["fermé","fermez","fermée"],e:"Après « il faut », l'infinitif : « fermer »."},
  {p:"Il met un ___ au bout de sa ligne.",i:"ver",r:["ver"],c:["vers","verre","vert"],e:"L'animal : « ver »."},
  {p:"Il boit un ___ d'eau.",i:"verre",r:["verre"],c:["ver","vers","vert"],e:"Le récipient : « verre »."},
  {p:"L'herbe est ___.",i:"verte",r:["verte"],c:["vertes","vairte","verre"],e:"La couleur au féminin : « verte »."},
  {p:"Il va ___ la gare.",i:"vers",r:["vers"],c:["ver","verre","vert"],e:"La direction : « vers »."},
  {p:"Il a une ___ sur la tête.",i:"bosse",r:["bosse"],c:["boss","bose","bossse"],e:"Deux s, e final."},
  {p:"Le ___ de la route.",i:"bord",r:["bord"],c:["bort","bore","bords"],e:"Le d final est muet."},
  {p:"Elle ___ trop vite.",i:"court",r:["court"],c:["cours","cour","courre"],e:"Le verbe : « elle court »."},
  {p:"La ___ de l'école.",i:"cour",r:["cour"],c:["court","cours","courre"],e:"L'espace ouvert : « cour »."},
  {p:"J'ai un ___ de maths.",i:"cours",r:["cours"],c:["cour","court","courts"],e:"La leçon : « cours »."},
  {p:"Une ___ de pain.",i:"tranche",r:["tranche"],c:["tranch","tranche's","tranches"],e:"E final au singulier."},
  {p:"Il ___ la vérité.",i:"dit",r:["dit"],c:["di","dis","dît"],e:"Le verbe au présent : « il dit »."},
  {p:"Des ___ sont amarrés au port.",i:"bateaux",r:["bateaux"],c:["bateaus","batteaux","batéaux"],e:"Pluriel en -eaux."},
  {p:"Ils ont les ___ sales.",i:"genoux",r:["genoux"],c:["genous","genouxs","genoues"],e:"« Genou » fait « genoux »."},
  {p:"Des ___ précieux.",i:"bijoux",r:["bijoux"],c:["bijous","bijouxs","bijoues"],e:"« Bijou » fait « bijoux »."},
  {p:"Les ___ chassent la nuit.",i:"hiboux",r:["hiboux"],c:["hibous","hibouxs","hiboues"],e:"« Hibou » fait « hiboux »."},
  {p:"Le chien creuse des ___ dans le jardin.",i:"trous",r:["trous"],c:["troux","troues","trou's"],e:"« Trou » fait « trous », sans x."},
  {p:"Des ___ de gâteau.",i:"morceaux",r:["morceaux"],c:["morceaus","morçeaux","morceau"],e:"Pluriel en -eaux."},
  {p:"Des ___ pointus.",i:"cailloux",r:["cailloux"],c:["caillous","caillouxs","caïlloux"],e:"« Caillou » fait « cailloux »."},
  {p:"Il a deux ___.",i:"animaux",r:["animaux"],c:["animals","animeaux","animaus"],e:"« Animal » fait « animaux »."},
  {p:"Les ___ de musique ont lieu en été.",i:"festivals",r:["festivals"],c:["festivaux","festivals'","festiveaux"],e:"Exception : « festival » fait « festivals »."},
  {p:"Il a vu plusieurs ___ cette année.",i:"carnavals",r:["carnavals"],c:["carnavaux","carnaval","carnavales"],e:"Exception : « carnaval » fait « carnavals »."},
  {p:"Le bus est ___ de monde.",i:"plein",r:["plein"],c:["plain","plin","pleint"],e:"Terminaison en -ein."},
  {p:"Il fait ___ de choses.",i:"beaucoup",r:["beaucoup"],c:["baucoup","beaucou","beaucoups"],e:"Le p final est muet."},
  {p:"Il est arrivé ___.",i:"hier",r:["hier"],c:["hièr","yer","ier"],e:"H muet initial."},
  {p:"C'est ___ gentil de ta part.",i:"vraiment",r:["vraiment"],c:["vraiement","vraimant","vréement"],e:"Pas de e avant -ment."},
  {p:"Il parle ___.",i:"gentiment",r:["gentiment"],c:["gentilment","gentiement","jentiment"],e:"Pas de l ni de e avant -ment."},
  {p:"Il court ___.",i:"rapidement",r:["rapidement"],c:["rapidemant","rappidement","rapidment"],e:"Terminaison en -ement."},
  {p:"Il est ___ gentil.",i:"très",r:["très"],c:["trés","tres","trè"],e:"Accent grave, s final."},
  {p:"Je pars ___.",i:"Aujourd'hui",r:["aujourd'hui"],c:["aujourdhui","aujourd'hui'","aujour d'hui"],e:"Apostrophe entre d et h."},
  {p:"Il y a un ___ dans ma soupe.",i:"cheveu",r:["cheveu"],c:["cheveux","chevu","chevo"],e:"Singulier : « cheveu » sans x."},
  {p:"Il faut ___ rire.",i:"en",r:["en"],c:["an","han","em"],e:"La préposition : « en »."},
  {p:"Il range ses affaires dans un ___.",i:"placard",r:["placard"],c:["plaquard","placar","plakard"],e:"Terminaison en -ard, le d final est muet."},
  {p:"La ___ s'accumule sous le lit.",i:"poussière",r:["poussière"],c:["pousière","poussiere","poussièrre"],e:"Deux s, accent grave, un seul r."},
  {p:"Il écrit une ___ à sa grand-mère.",i:"lettre",r:["lettre"],c:["lètre","letre","lettrre"],e:"Deux t, pas d'accent."},
  {p:"Un ___ de vin.",i:"tonneau",r:["tonneau"],c:["toneau","tonau","tonneaux"],e:"Deux n, terminaison en -eau au singulier."},
  {p:"Ce ___ est très confortable.",i:"fauteuil",r:["fauteuil"],c:["fauteil","fauteuille","fotueil"],e:"Terminaison en -euil, sans e."},
  {p:"Elle porte un joli ___.",i:"collier",r:["collier"],c:["colier","collié","collièr"],e:"Deux l, terminaison en -ier."},
  {p:"L'___ est au deuxième étage.",i:"appartement",r:["appartement"],c:["apartement","appartemment","appartemant"],e:"Deux p, un seul m, terminaison en -ment."},
  {p:"Il a une grande ___ dans son jardin.",i:"pelouse",r:["pelouse"],c:["pelouze","pelousse","pellouse"],e:"Un seul l, un seul s prononcé z."},
  {p:"Mets un ___ dans ton verre.",i:"glaçon",r:["glaçon"],c:["glasson","glacon","glaçons"],e:"Cédille sous le c devant le o."},
  {p:"Le chat fait ses ___ sur le tapis.",i:"griffes",r:["griffes"],c:["grifes","griffe","grriffes"],e:"Deux f, et le s du pluriel."},
  {p:"Une ___ de chocolat chaud.",i:"tasse",r:["tasse"],c:["tase","tâsse","tasses"],e:"Deux s, sans accent."},
  {p:"Il met son ___ pour sortir.",i:"blouson",r:["blouson"],c:["blousson","blouzon","bloussont"],e:"Un seul s, prononcé z."},
  {p:"La ___ vole au-dessus de la mer.",i:"mouette",r:["mouette"],c:["mouète","mouete","mouettes"],e:"Deux t, terminaison en -ette."},
  {p:"Il a peint un ___ magnifique.",i:"tableau",r:["tableau"],c:["tablau","tabbleau","tableaux"],e:"Terminaison en -eau, sans x au singulier."},
  {p:"Il a le ___ rouge après le sport.",i:"visage",r:["visage"],c:["vizage","visaje","vissage"],e:"Un seul s, prononcé z entre deux voyelles."},
  {p:"La ___ de ma chambre est bleue.",i:"peinture",r:["peinture"],c:["pinture","painture","peintur"],e:"Le son « in » s'écrit -ein-."},
  {p:"Le petit ___ dort dans son berceau.",i:"bébé",r:["bébé"],c:["bebe","bêbé","bébés"],e:"Deux accents aigus."},
  {p:"Elle est ___ de sa robe.",i:"fière",r:["fière"],c:["fier","fiere","fièrre"],e:"Au féminin : fière, avec un accent grave."},
  {p:"Vous ___ très gentils.",i:"êtes",r:["êtes"],c:["etes","ètes","êtez"],e:"Accent circonflexe : vous êtes."},
  {p:"Le ___ garde les moutons.",i:"berger",r:["berger"],c:["bergé","berjer","bergers"],e:"Terminaison en -er, le g se prononce j devant e."},
  {p:"Le train part du ___ numéro trois.",i:"quai",r:["quai"],c:["quay","kai","quais"],e:"Qu- au début, -ai à la fin."},
  {p:"Le ___ de la voiture est crevé.",i:"pneu",r:["pneu"],c:["pneux","peneu","pneut"],e:"Pas de x au singulier."},
  {p:"Il a mis du ___ dans son café.",i:"sucre",r:["sucre"],c:["sucr","succre","suchre"],e:"Un seul c, e final."},
  {p:"Il lit un ___ de bandes dessinées.",i:"album",r:["album"],c:["albom","albume","alboum"],e:"Terminaison en -um, prononcée « ome »."},
  {p:"Le ___ du village sonne midi.",i:"clocher",r:["clocher"],c:["clochet","cloché","clauché"],e:"Terminaison en -er."},
  {p:"Il a mis la table pour le ___.",i:"repas",r:["repas"],c:["repat","repa","reppas"],e:"Le s final est muet."},
  {p:"Le ___ remonte la rivière.",i:"saumon",r:["saumon"],c:["saumond","somon","saumont"],e:"Au- pour le son « o »."},
  {p:"Il boit un verre de ___.",i:"lait",r:["lait"],c:["laid","lai","laie"],e:"La boisson : « lait »."},
  {p:"Il a couru ___ kilomètres.",i:"cent",r:["cent"],c:["sans","sent","cents"],e:"Le nombre : « cent », sans s ici."},
  {p:"Il a ___ ans aujourd'hui.",i:"vingt",r:["vingt"],c:["vint","vain","vingts"],e:"Le nombre : « vingt », avec g et t muets."},
  {p:"Il a acheté du ___ à la boulangerie.",i:"pain",r:["pain"],c:["pin","pein","paint"],e:"L'aliment : « pain »."},
  {p:"Elle a un ___ au bras après sa chute.",i:"bleu",r:["bleu"],c:["bleux","bleue","bleus"],e:"Le nom au singulier : « un bleu »."},
  {p:"Il ___ ses clés partout.",i:"perd",r:["perd"],c:["pert","per","perds"],e:"« Il perd » : d à la 3e personne."},
  {p:"Tu ___ le bus tous les jours.",i:"prends",r:["prends"],c:["prend","prens","prands"],e:"« Tu prends » : d et s."},
  {p:"Nous ___ au parc.",i:"allons",r:["allons"],c:["alons","allont","allon"],e:"Deux l, terminaison en -ons."},
  {p:"Ils ___ leurs devoirs.",i:"font",r:["font"],c:["fon","fons","fonts"],e:"« Ils font » : terminaison en -ont."},
  {p:"Je ___ content de te voir.",i:"suis",r:["suis"],c:["suit","sui","suie"],e:"« Je suis » : s final."},
  {p:"Elle se ___ les dents.",i:"brosse",r:["brosse"],c:["brose","brausse","brosses"],e:"Deux s, e final."},
  {p:"La ___ a mangé le fromage.",i:"souris",r:["souris"],c:["sourie","sourit","souri"],e:"« Souris » prend un s même au singulier."},
  {p:"Elle a gagné la ___.",i:"course",r:["course"],c:["cource","coursse","courses"],e:"Un seul s, e final."},
  {p:"Les ___ de Noël brillent.",i:"guirlandes",r:["guirlandes"],c:["girlandes","guirlande","guirlandent"],e:"Gu- devant i, et le s du pluriel."},
  {p:"C'est un ___ célèbre.",i:"acteur",r:["acteur"],c:["hacteur","acteure","akteur"],e:"Terminaison en -eur, sans e."},
  {p:"Elle ouvre son ___ pour payer.",i:"portefeuille",r:["portefeuille"],c:["portefeuil","portefeille","portfeuille"],e:"Un seul mot, terminaison en -euille."},
  {p:"Mon ___ habite à Lyon.",i:"cousin",r:["cousin"],c:["cousain","cousint","cousins"],e:"Terminaison en -in, sans t."},
  {p:"Elle a acheté des ___ au marché.",i:"carottes",r:["carottes"],c:["carotes","carrottes","carrotes"],e:"Un seul r, deux t."},
  {p:"Ils jouent au ___ dans la cour.",i:"ballon",r:["ballon"],c:["balon","bâllon","ballons"],e:"Deux l, sans accent."},
  {p:"Nous mangeons des ___ au dessert.",i:"fraises",r:["fraises"],c:["fraizes","fréses","fraisses"],e:"Un seul s, prononcé z."},
  {p:"Il faut ___ ses mains avant de manger.",i:"laver",r:["laver"],c:["lavé","lavez","lavait"],e:"Après « il faut », l'infinitif en -er."},
  {p:"Nous partons en ___ scolaire.",i:"sortie",r:["sortie"],c:["sorti","sortit","sortis"],e:"Le nom féminin : « une sortie »."},
  {p:"Un ___ de journal.",i:"article",r:["article"],c:["artikle","articcle","artiscle"],e:"Un seul c, terminaison en -cle."}
];
